# Generated by Django 4.0.4 on 2022-04-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produkts',
            new_name='Products',
        ),
    ]
