# Generated by Django 4.0.4 on 2022-04-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_produkts_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
