# Generated by Django 4.0.4 on 2022-04-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_producer_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.producer'),
        ),
    ]
